// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zadjehlurkkyjrfuavtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZGplaGx1cmtreWpyZnVhdnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzYzMjIsImV4cCI6MjA3MjExMjMyMn0.uovq_ob0T4qZorPW2lMaCQxtPIOSU6nz81mCPiX00i8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});